image:
  - Visual Studio 2017

configuration:
  - Release

build_script:
  - cmd: scripts/build_win.bat

artifacts:
  - path: ./out/
    name: PSDtoSS6_win

deploy:
  provider: GitHub
  auth_token:
    secure: SgBhPSveSRK+d8WTCvl/MvIwm8IA6ZlCk5BJtFpnio+H5/Fj+ocZz3GbkRc+W2Cv
  artifact: PSDtoSS6_win.zip
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only